-- Tabela de feedbacks das fisioterapeutas
create table if not exists public.feedback_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  author text null,
  message text not null,
  status text not null default 'pending', -- pending | sent
  sent_at timestamptz null,
  device text null,
  page text not null default 'home'
);

-- Índices para ordenar e filtrar
create index if not exists feedback_messages_created_at_idx on public.feedback_messages (created_at desc);
create index if not exists feedback_messages_status_idx on public.feedback_messages (status);

-- Caso o projeto esteja com RLS ativado, habilite políticas permissivas para o app (anon):
-- alter table public.feedback_messages enable row level security;
-- create policy "Allow anon read feedback" on public.feedback_messages for select using (true);
-- create policy "Allow anon insert feedback" on public.feedback_messages for insert with check (true);
-- create policy "Allow anon update feedback status" on public.feedback_messages for update using (true);
